version: '3.8'

services:
  verseapp.api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-test
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: Oracle123!
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: